### ISSUE TITLE
Professor Oak deployment checklist DEADLINE:

### ISSUE THREAD

**Issue by canismarko** [canismarko/professor_oak#39]
To help in the transition, let's make sure we have all the steps defined for Monday:
- [x] Pull latest github changes to geodude
- [x] Collect static, apply migrations and restart server & clear cache
- [x] Load cabana users from fixture
- [x] Delete all `Chemical` and `Container` instances

---
- [x] Shutdown old chemical inventory
- [x] Dump CAS and INVENT tables
- [x] Copy MSDS folder to geodude
- [x] Import CAS and INVENT tables into geodude database

---
- [x] Fix Location descriptors
- [x] Marvel at the [stunning inability](http://imgur.com/xrX4VV0) of our group to properly use the old database
- [x] Beer

**Comment by michaelplews** [comment]
Hooray!
